/** @type {import("stylelint").Config} */
export default {
    extends: [
        'stylelint-config-standard',
        'stylelint-config-recess-order',
        'stylelint-config-standard-scss',
        'stylelint-prettier/recommended',
    ],
    plugins: ['stylelint-prettier', 'stylelint-order'],
    customSyntax: 'postcss-scss',
    defaultSeverity: 'warning',
    rules: {
        'alpha-value-notation': 'number',
        'color-function-notation': 'modern',
        'declaration-block-no-redundant-longhand-properties': true,
        'declaration-block-single-line-max-declarations': 1,
        'declaration-property-value-disallowed-list': {
            '/^transition/': ['/all/'],
            '/^background/': ['http:'],
            border: ['none'],
        },
        'font-family-no-missing-generic-family-keyword': true,
        'function-disallowed-list': ['rgb', 'rgba', 'hsl', 'hsla'],
        'function-url-quotes': 'always',
        'length-zero-no-unit': true,
        'media-feature-range-notation': 'context',
        'no-duplicate-selectors': true,
        'no-empty-source': null,
        'no-invalid-position-at-import-rule': true,
        'number-max-precision': 3,
        'property-no-vendor-prefix': true,
        'rule-empty-line-before': [
            'always-multi-line',
            {
                except: ['first-nested'],
                ignore: ['after-comment'],
            },
        ],
        'selector-class-pattern': '^[a-z][a-zA-Z0-9]+(__[a-z][a-zA-Z0-9]+)?(--[a-z][a-zA-Z0-9]+)?$',
        'selector-id-pattern': null,
        'selector-no-qualifying-type': true,
        'selector-pseudo-element-colon-notation': 'double',
        'selector-type-case': 'lower',
        'shorthand-property-no-redundant-values': true,
        'value-keyword-case': 'lower',
        'value-no-vendor-prefix': true,

        'scss/at-rule-no-unknown': true,
        'scss/comment-no-loud': true,
        'scss/double-slash-comment-whitespace-inside': 'always',
        'scss/no-duplicate-dollar-variables': true,
        'scss/operator-no-unspaced': true,
    },
};
